const FileData = {
    "games": [
        {"hoverString": "www.neopets.com",
        "src": "images/neopetsicon.png",
        "scale": 0.55,
        "x": 20,
        "y": 270},
        {"hoverString": "https://jstris.jezevec10.com/",
        "src": "images/tetris.png",
        "scale": 0.55,
        "x": 300,
        "y": 140},
        {"hoverString": "https://jstris.jezevec10.com/",
        "src": "images/com.png",
        "scale": 0.55,
        "x": 400,
        "y": 160},
        {"hoverString": "( Kingdom of Loathing )",
        "src": "images/kolicon.png",
        "scale": 0.55,
        "x": 280,
        "y": 100},
        {"hoverString": "( Spider and Web )",
        "src": "images/spiderweb.png",
        "scale": 0.55,
        "x": 180,
        "y": 50},
        {"hoverString": "Club Penguin",
        "src": "images/cp.png",
        "scale": 0.55,
        "x": 640,
        "y": 350},
        {"hoverString": "Shift",
        "src": "images/shift.png",
        "scale": 0.55,
        "x": 580,
        "y": 270},
        {"hoverString": "Fantage",
        "src": "images/fantage.png",
        "scale": 0.55,
        "x": 820,
        "y": 390},
        {"hoverString": "Loved",
        "src": "images/loved.png",
        "scale": 0.55,
        "x": 420,
        "y": 30},
        {"hoverString": "( a dark room )",
        "src": "images/darkroom.png",
        "scale": 0.55,
        "x": -50,
        "y": 170}
      ],
    "misc": [
        {"hoverString": "TRShady",
        "src": "images/trshady.png",
        "scale": 0.45,
        "x": 820,
        "y": 480},
        {"hoverString": "windows93",
        "src": "images/windows93.png",
        "scale": 0.45,
        "x": 30,
        "y": 370},
        {"hoverString": "are.na",
        "src": "images/arena.png",
        "scale": 0.55,
        "x": 610,
        "y": 410},
        {"hoverString": "( daily deviation dream )",
        "src": "images/deviantart.png",
        "scale": 0.55,
        "x": 710,
        "y": 450},
        {"hoverString": "( MSCHF )",
        "src": "images/mschf.png",
        "scale": 0.55,
        "x": 910,
        "y": 420}
    ],
    "text": [
        {"hoverString": "archiveofourown.org",
        "src": "images/ao3icon.png",
        "scale": 0.53,
        "x": 150,
        "y": 120},
        {"hoverString": "www.tvtropes.org",
        "src": "images/tvtropes.png",
        "scale": 0.55,
        "x": 250,
        "y": 120},
        {"hoverString": "Rational Wiki",
        "src": "images/rational.png",
        "scale": 0.55,
        "x": 760,
        "y": 420},
        {"hoverString": "( scp foundation )",
        "src": "images/scp.png",
        "scale": 0.55,
        "x": 440,
        "y": 435},
        {"hoverString": "( Edit Wars )",
        "src": "images/wiki.png",
        "scale": 0.55,
        "x": 530,
        "y": 120}
    ],
    "windows": [
        {"hoverString": "૮꒰ ˶• ༝ •˶꒱ა ♡",
        "src": "images/kaomoji.png",
        "scale": 0.5,
        "border": true,
        "x": 720,
        "y": 150},
        {"hoverString": "( Girlhood )",
        "src": "images/emojis.png",
        "scale": 0.55,
        "border": true,
        "x": 560,
        "y": 40},
        {"hoverString": "( 🌐🤍🎀🫧 )",
        "src": "images/internet.png",
        "scale": 0.50,
        "border": true,
        "x": 110,
        "y": 310}
    ]
}

export default FileData;
