const FileData = {
    "games": [
        {"hoverString": "www.neopets.com",
        "src": "images/neopetsicon.png",
        "url": "https://www.neopets.com/",
        "scale": 0.55,
        "x": 20,
        "y": 270},
        {"hoverString": "https://jstris.jezevec10.com/",
        "url": "https://jstris.jezevec10.com/",
        "src": "images/tetris.png",
        "scale": 0.55,
        "x": 300,
        "y": 140},
        {"hoverString": "The Company of Myself",
        "src": "images/com.png",
        "url": "https://www.newgrounds.com/portal/view/518729",
        "scale": 0.55,
        "x": 400,
        "y": 160},
        {"hoverString": "( Kingdom of Loathing )",
        "src": "images/kolicon.png",
        "url": "https://www.kingdomofloathing.com/",
        "scale": 0.55,
        "x": 280,
        "y": 100},
        {"hoverString": "( Spider and Web )",
        "src": "images/spiderweb.png",
        "url": "https://eblong.com/zarf/zweb/tangle/",
        "scale": 0.55,
        "x": 180,
        "y": 50},
        {"hoverString": "Club Penguin",
        "src": "images/cp.png",
        "url": "https://www.cplegacy.com/",
        "scale": 0.55,
        "x": 640,
        "y": 350},
        {"hoverString": "Shift",
        "src": "images/shift.png",
        "url": "https://armorgames.com/play/751/shift",
        "scale": 0.55,
        "x": 580,
        "y": 270},
        {"hoverString": "Fantage",
        "src": "images/fantage.png",
        "url": "https://en.wikipedia.org/wiki/Fantage",
        "scale": 0.55,
        "x": 820,
        "y": 390},
        {"hoverString": "Loved",
        "src": "images/loved.png",
        "url": "https://ocias.com/works/loved/",
        "scale": 0.55,
        "x": 420,
        "y": 30},
        {"hoverString": "( a dark room )",
        "src": "images/darkroom.png",
        "url": "https://adarkroom.doublespeakgames.com/",
        "scale": 0.55,
        "x": -50,
        "y": 170}
      ],
    "misc": [
        {"hoverString": "TRShady",
        "src": "images/trshady.png",
        "url": "http://forum.trshady.com/",
        "scale": 0.55,
        "x": 820,
        "y": 480},
        {"hoverString": "windows93",
        "src": "images/windows93.png",
        "url": "https://www.windows93.com/",
        "scale": 0.55,
        "x": 30,
        "y": 370},
        {"hoverString": "are.na",
        "src": "images/arena.png",
        "url": "https://www.are.na/",
        "scale": 0.55,
        "x": 610,
        "y": 410},
        {"hoverString": "( daily deviation dream )",
        "src": "images/deviantart.png",
        "url": "https://www.deviantart.com/",
        "scale": 0.55,
        "x": 710,
        "y": 450},
        {"hoverString": "( MSCHF )",
        "src": "images/mschf.png",
        "url": "https://www.mschf.com/",
        "scale": 0.55,
        "x": 910,
        "y": 420}
    ],
    "text": [
        {"hoverString": "archiveofourown.org",
        "src": "images/ao3icon.png",
        "url": "https://archiveofourown.org/",
        "scale": 0.53,
        "x": 150,
        "y": 120},
        {"hoverString": "www.tvtropes.org",
        "src": "images/tvtropes.png",
        "url": "https://www.tvtropes.org/",
        "scale": 0.55,
        "x": 250,
        "y": 120},
        {"hoverString": "Rational Wiki",
        "src": "images/rational.png",
        "url": "https://rationalwiki.org/wiki/Special:Random",
        "scale": 0.55,
        "x": 760,
        "y": 420},
        {"hoverString": "( scp foundation )",
        "src": "images/scp.png",
        "url": "https://scp-wiki.wikidot.com/",
        "scale": 0.55,
        "x": 440,
        "y": 435},
        {"hoverString": "( Edit Wars )",
        "src": "images/wiki.png",
        "url": "https://en.wikipedia.org/wiki/Wikipedia:Edit_wars",
        "scale": 0.55,
        "x": 530,
        "y": 120}
    ],
    "windows": [
        {"hoverString": "૮꒰ ˶• ༝ •˶꒱ა ♡",
        "src": "images/kaomoji.png",
        "scale": 0.5,
        "border": true,
        "x": 720,
        "y": 150},
        {"hoverString": "( Girlhood )",
        "src": "images/emojis.png",
        "scale": 0.55,
        "border": true,
        "x": 560,
        "y": 40},
        {"hoverString": "( 🌐🤍🎀🫧 )",
        "src": "images/internet.png",
        "scale": 0.50,
        "border": true,
        "x": 110,
        "y": 310}
    ]
}

export default FileData;
